ci/github: Set SOURCE_DATE_EPOCH
CentOS/centos-boot pull request #24
Opened 2023-11-06 22:19 UTC by cgwalters

This is important since it turns on some rpm-ostree reproducibility bits. TODO: replicate with RHTAP

2023-11-06 22:20 UTC, cgwalters commented
[a bit surprising](https://github.com/search?q=repo%3Aredhat-appstudio%2Fbuild-definitions%20SOURCE_DATE_EPOCH&type=code)

2023-11-08 07:54 UTC, lmilbaum requested changes
I'd suggest to move those bits to the publish-image.yml file. The CI workflow is just checking the build is successful while the publish image workflow, which is triggered after the PR is merged, is the one which pushes the image to quay.io

2023-11-08 14:55 UTC, cgwalters commented
Right.  I guess this really gets into a larger question I have around why nothing in RHTAP (AFAICS) is dealing with `SOURCE_DATE_EPOCH`.  I can't even find any references to it in the Tekton ecosystem in general.

2023-11-08 14:56 UTC, cgwalters commented
Anyways updated the `publish-image` flow too

2023-11-08 16:01 UTC, cgwalters commented
Ahh this needs https://github.com/CentOS/centos-boot/pull/38

2023-11-08 17:27 UTC, lmilbaum commented
#38 merged. please rebase.

2023-11-09 22:29 UTC, cgwalters commented
OK so we merged #38 but then we merged [https://github.com/CentOS/centos-boot/pull/45 which effectively ](https://github.com/CentOS/centos-boot/commit/0c477331a83bc87cbe1c5bb61df44b0052641e73) which reverted it...and now the builds are broken again because quay.io pretty aggressively GCs unreferenced images...

2023-11-17 20:28 UTC, merged